"""Shared configuration for HAL language training and visualization."""

# Grid configuration
TILE_COUNT_X = 128
TILE_COUNT_Y = 128
LOGICAL_TILE_WIDTH = 16
LOGICAL_TILE_HEIGHT = 16
VISUAL_SCALE = 2  # half previous scale
TILE_GAP = 0
ORIGIN_X = 12
ORIGIN_Y = 12

# Viewport / camera
WINDOW_WIDTH = 1440
WINDOW_HEIGHT = 900
VIEW_TILES_X = 32
VIEW_TILES_Y = 24
CAMERA_SPEED_CELLS = 4

# Vision configuration
RENDER_DISTANCE_TILES = 3
FOV_DEGREES = 45
NUM_VISION_RAYS = 61

# Language/Q-table configuration
WORD_SPACE_SIZE = 10000
LEARNING_STEPS = 220
LEXICON_OBJECT_TYPES = ("apple", "mushroom")
LEXICON_COLOR_NAMES = ("red", "orange", "yellow", "green", "blue", "indigo", "violet")
NOISE_SCALE = 0.045
MIN_NOISE_SCALE = 0.004
WTA_GAIN = 0.12
WTA_DECAY = 0.003
COMM_LR = 0.32
SOCIAL_LR = 1.15
SELF_PENALTY_LR = 0.24
CONSENSUS_STREAK_TARGET = 8

# Subjective belief / search behavior
BELIEF_OBS_HIT = 0.82
BELIEF_OBS_NONE = 0.82
BELIEF_DRIFT = 0.002
BELIEF_TARGET_THRESHOLD = 0.22
BELIEF_STALE_AFTER_FRAMES = 180
BELIEF_STALE_REVERT = 0.6
SCAN_ROTATIONS = (0, 90, 180, 270)
SCAN_AT_FRONTIER = True

# Command grounding + movement
COMMAND_PRETRAIN_EPISODES = 1200
COMMAND_PRETRAIN_EPSILON = 0.22
COMMAND_PRETRAIN_LR = 0.18
COMMAND_INTERVAL_FRAMES = 110
MAX_COMMAND_PATH_STEPS = 24
SPEECH_BUBBLE_FRAMES = 60
FEEDBACK_BUBBLE_FRAMES = 45
COMMAND_FIND_TARGET_OUTSIDE_LOS = True
COMMAND_FETCH_MOVE_COOLDOWN = 2
COMMAND_MAX_FETCH_STEPS = 40
COMMAND_AUTO_FIND_RATE = 0.34
COMMAND_PANEL_SHOW_VERBOSE = True

# Cave generation
CAVE_FILL_PROB = 0.44
CAVE_SMOOTH_STEPS = 5
CAVE_BIRTH_LIMIT = 4
CAVE_SURVIVE_LIMIT = 3

# UI panel configuration
PANEL_WIDTH = 420
PANEL_MARGIN = 10
LINE_HEIGHT = 20
INVENTORY_BAR_HEIGHT = 110

# Logging
ARTIFACTS_DIR = "artifacts"
